dspace.cfg: disable old WordFilter extractor
The old filter crashes with an error like:

    Exception: org.apache.poi.util.LittleEndian.getUnsignedByte([BI)I
    java.lang.NoSuchMethodError: org.apache.poi.util.LittleEndian.getUnsignedByte([BI)I
	    at org.textmining.extraction.word.model.FormattedDiskPage.<init>(FormattedDiskPage.java:66)
	    at org.textmining.extraction.word.model.CHPFormattedDiskPage.<init>(CHPFormattedDiskPage.java:62)
	    at org.textmining.extraction.word.model.CHPBinTable.<init>(CHPBinTable.java:70)
	    at org.textmining.extraction.word.Word97TextExtractor.getText(Word97TextExtractor.java:122)
	    at org.textmining.extraction.word.Word97TextExtractor.getText(Word97TextExtractor.java:63)
	    at org.dspace.app.mediafilter.WordFilter.getDestinationStream(WordFilter.java:83)
            ...

According to a thread from 2018-12 on the dspace-tech mailing list,
the old filter will be removed in future DSpace releases. We should
be using the newer PoiWordFilter.